### ISSUE TITLE
Set correct meta information + contract name + constructor id

### ISSUE THREAD

**Issue by rasmuscnielsen** [Developer-DAO/ukraine-donation-nft#22]
Just so we don't forget it this time around :-) 

Once we figure out the official name for the NFT we might also want to rename the contract filename (unless that's the name we roll with). 
We might want to get that sorted soon so it's not a last minute change lol

**Comment by briangershon** [comment]
The name in the contract is currently `PXLDEV-UKRAINE`. Is that ok, or should we change it?

**Comment by rasmuscnielsen** [comment]
@briangershon So far I've been rolling with `Ukraine Donation NFT` everywhere in the web client. I guess also given that the project is now quite independent from Pixel Devs except for the wearable part in the roadmap. 

But maybe its worth playing around with the naming a bit to make it more interesting.. Quick brainstorm

- Fund Ukraine
- Support Ukraine 
- Humanity for Ukraine
- Developer DAO for Ukraine
- ... Ukraine 4 Revolution? 😅

Feel free to come up with more ideas. If we have a few in the mix, we could share them in Discord. 

Once we have a final name, perhaps we wanna update 

- [ ] Contract top comments
- [ ] Constructor NAME + SYMBOL
- [ ] Perhaps contract filename if we dare? :-) 
```
/// @author Developer DAO
/// @title The Pixel Devs Ukraine Donation smart contract that is compliant to ERC721 standard.
contract PixelDevsUkraineDonation is
```

```
constructor() ERC721("PixelDevsUkraineDonation", "PXLDEV-UKRAINE") {
```

**Comment by briangershon** [comment]
Hey @rasmuscnielsen I think we can run with "Developer DAO for Ukraine" naming.

We can make these changes as part of PR #30 which is wrapping up a bunch of odds'n'ends such as #28 #22 #14.

I'm happy to work on this as part of the effort to update the site based on new FAQ in doc. Or if you have any spare cycles, feel free to run with updating site title or anything there.

**Comment by rasmuscnielsen** [comment]
@briangershon Yes let's run with that one! 

Please feel free to take on as much as you're comfortable with! 
And as mentioned on Discord if there are any specific tasks you'd like my help with please feel free to bundle it and ping me. Then I'll try and fit it in before launch date (whenever that is lol). 

Thanks for being a champ, Brian!
